package com.raghavrp.hospital;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cache.annotation.EnableCaching;

/**
 * Entry point for the Hospital Management System.
 *
 * What runs on startup:
 *  - H2 in-memory database created + tables generated by JPA
 *  - data.sql seeds sample doctors, patients, users
 *  - Redis cache enabled (@EnableCaching)
 *  - JWT security filter chain activated
 *  - Swagger UI available at http://localhost:8081/swagger-ui.html
 */
@SpringBootApplication
@EnableCaching   // activates @Cacheable, @CacheEvict, @CachePut across all beans
public class HospitalManagementApplication {
    public static void main(String[] args) {
        SpringApplication.run(HospitalManagementApplication.class, args);
    }
}
